DROP TABLE IF EXISTS users  CASCADE;
CREATE TABLE users (
id SERIAL PRIMARY KEY,
first VARCHAR NOT NULL,
last VARCHAR NOT NULL,
email VARCHAR NOT NULL UNIQUE,
imageUrl TEXT,
bio TEXT,
password VARCHAR NOT NULL
);
